# Generated by Django 5.2.1 on 2025-05-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprogram',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='사용 여부'),
        ),
    ]
