# Generated by Django 5.2.1 on 2025-05-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_program', '0002_productprogram_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprogram',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
    ]
