# Generated by Django 5.2.1 on 2025-05-28 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_info', '0002_alter_product_options_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('mix', '혼입 점검'), ('box', '포장 점검')], max_length=10, verbose_name='점검 구분')),
                ('result', models.CharField(default='오류', max_length=10, verbose_name='결과')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='점검 시간')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_info.product', verbose_name='제품')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
            ],
        ),
    ]
