# Generated by Django 5.2.1 on 2025-05-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': '제품', 'verbose_name_plural': '제품 목록'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='제품 이미지'),
        ),
    ]
