# Generated by Django 5.2.1 on 2025-06-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_info', '0002_alter_product_options_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pallet_box_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='파레트 적재 박스 수량'),
        ),
    ]
